# docker build -t roadchat:dev -f Dockerfile-dev . && docker run -it -p 8080:8080 -v "$PWD":/app --privileged --rm roadchat:dev

FROM norionomura/swift:swift-4.1-branch
RUN apt-get -qq update && apt-get -q -y install pkg-config openssl libssl-dev
  # your-dependencies-here # e.g. libmysqlclient-dev libpq-dev etc
WORKDIR /app
